export const RECOVER_FILES = 'RECOVER_FILES';
export const RECOVER_FILES_NOK = 'RECOVER_FILES_NOK';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_OK = 'UPLOAD_FILE_OK';
export const UPLOAD_FILE_NOK = 'UPLOAD_FILE_NOK';

export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const DOWNLOAD_FILE_OK = 'DOWNLOAD_FILE_OK';
export const DOWNLOAD_FILE_NOK = 'DOWNLOAD_FILE_NOK';