// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:dfe77a91-fa03-4402-8b78-4a9a1ee90ad6",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_TVjTDi2kY",
    "aws_user_pools_web_client_id": "3sj3f1fd7dooohoir46gvajqt1",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS",
    "aws_user_files_s3_bucket": "media-cloud-ionic8388177d8b1047899f9c69592bad4cionic-mdenv",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_content_delivery_bucket": "media-cloud-host-mdenv",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://media-cloud-host-mdenv.s3-website-eu-west-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://6kspkodjl5frvmwsiu2afyswci.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
